apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}
  labels:
    {{- include "integrierte-genomische-surveillance-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.fullName }}
