# Actuator Configuration
management:
  observations:
    key-values:
      application: name
# Information for the /info Endpoint
info:
  app:
    name: name
    version: version

spring:
  config:
    import: classpath:/base-config-application.yaml
  servlet:
    multipart:
      max-file-size: 998MB
      max-request-size: 998MB
simple:
  storage:
    service:
      url: ${S3_URL:http://localhost:9000}
      cluster-url: ${S3_CLUSTER_URL:http://minio.demis.svc.cluster.local}
      access-key: ${S3_ACCESS_KEY:my-local-minio-user}
      secret-key: ${S3_SECRET_KEY:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG}
      upload-bucket:
        name: ${S3_BUCKET:sequence-data}
        deletion-deadline-in-days: ${S3_DELETION_DEADLINE_FOR_INVALID_BUCKET_IN_DAYS:2}
      validated-bucket:
        name: ${S3_VALID_BUCKET:sequence-data-valid}
        deletion-deadline-in-days: ${S3_DELETION_DEADLINE_FOR_VALID_BUCKET_IN_DAYS:32}
      multipart-max-upload-size-in-bytes: ${S3_MULTIPART_MAX_UPLOAD_SIZE:1073741824} # 1GB
      multipart-upload-chunk-size-in-bytes: ${S3_MULTIPART_UPLOAD_CHUNK_SIZE:10485760} # 10MB
      signed-url-expiration-in-minutes: ${S3_SIGNED_URL_EXPIRATION_IN_MINUTES:720} # 12 hours
      storage-tls-certificate: ${S3_STORAGE_TLS_CERTIFICATE:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQW5lZ0F3SUJBZ0lVVzhCNUZ6UmdRNkxRUnNwSktrc0JrWmZ4MTJjd0NnWUlLb1pJemowRUF3SXcKY3pFTE1Ba0dBMVVFQmhNQ1JFVXhEekFOQmdOVkJBZ01Ca0psY214cGJqRVBNQTBHQTFVRUJ3d0dRbVZ5YkdsdQpNUlV3RXdZRFZRUUtEQXhuWlcxaGRHbHJJRWR0WWtneERqQU1CZ05WQkFzTUJVUkZUVWxUTVJzd0dRWURWUVFECkRCSmhkWFJvTG1sdVozSmxjM011Ykc5allXd3dIaGNOTWpRd09ESTRNRGMwTkRVMFdoY05NelF3T0RJNE1EYzAKTkRVMFdqQnpNUXN3Q1FZRFZRUUdFd0pFUlRFUE1BMEdBMVVFQ0F3R1FtVnliR2x1TVE4d0RRWURWUVFIREFaQwpaWEpzYVc0eEZUQVRCZ05WQkFvTURHZGxiV0YwYVdzZ1IyMWlTREVPTUF3R0ExVUVDd3dGUkVWTlNWTXhHekFaCkJnTlZCQU1NRW1GMWRHZ3VhVzVuY21WemN5NXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUgKQTBJQUJMS09nV1RSdDMza2JrcStSMGI5MjRXWmlCVGRoekdmQ09RTkxmZnVQMmFLUU5IQlRHWkpUWEU2ZWlIYwpibjdGaFR5eWFuYjRTd2lMUEE4NVBGT2NZRXlqZ2Vnd2dlVXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01INEdBMVVkCkVRUjNNSFdDRW1GMWRHZ3VhVzVuY21WemN5NXNiMk5oYklJWVluVnVaR2xrTFdsa2NDNXBibWR5WlhOekxteHYKWTJGc2dobHBaM010YzNSdmNtRm5aUzVwYm1keVpYTnpMbXh2WTJGc2doUndiM0owWVd3dWFXNW5jbVZ6Y3k1cwpiMk5oYklJVWRHa3RhV1J3TG1sdVozSmxjM011Ykc5allXd3dId1lEVlIwakJCZ3dGb0FVZFN4ek1uQkMxSGVyCkNUejMzRVhwdG1FV1ZXVXdIUVlEVlIwT0JCWUVGSFVzY3pKd1F0UjNxd2s4OTl4RjZiWmhGbFZsTUJNR0ExVWQKSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRGgzaUNBNXBEM1RrREtCbUp3VApZOVY0aUx1allhclVGMmJxWDlLbFZxa2NBaUFhazZ2Z3dTL2RtNGpMc3JxblpjazhaK2RjT0dkWExqWkFxZURhCk1LbnRKUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQW5lZ0F3SUJBZ0lVVzhCNUZ6UmdRNkxRUnNwSktrc0JrWmZ4MTJjd0NnWUlLb1pJemowRUF3SXcKY3pFTE1Ba0dBMVVFQmhNQ1JFVXhEekFOQmdOVkJBZ01Ca0psY214cGJqRVBNQTBHQTFVRUJ3d0dRbVZ5YkdsdQpNUlV3RXdZRFZRUUtEQXhuWlcxaGRHbHJJRWR0WWtneERqQU1CZ05WQkFzTUJVUkZUVWxUTVJzd0dRWURWUVFECkRCSmhkWFJvTG1sdVozSmxjM011Ykc5allXd3dIaGNOTWpRd09ESTRNRGMwTkRVMFdoY05NelF3T0RJNE1EYzAKTkRVMFdqQnpNUXN3Q1FZRFZRUUdFd0pFUlRFUE1BMEdBMVVFQ0F3R1FtVnliR2x1TVE4d0RRWURWUVFIREFaQwpaWEpzYVc0eEZUQVRCZ05WQkFvTURHZGxiV0YwYVdzZ1IyMWlTREVPTUF3R0ExVUVDd3dGUkVWTlNWTXhHekFaCkJnTlZCQU1NRW1GMWRHZ3VhVzVuY21WemN5NXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUgKQTBJQUJMS09nV1RSdDMza2JrcStSMGI5MjRXWmlCVGRoekdmQ09RTkxmZnVQMmFLUU5IQlRHWkpUWEU2ZWlIYwpibjdGaFR5eWFuYjRTd2lMUEE4NVBGT2NZRXlqZ2Vnd2dlVXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01INEdBMVVkCkVRUjNNSFdDRW1GMWRHZ3VhVzVuY21WemN5NXNiMk5oYklJWVluVnVaR2xrTFdsa2NDNXBibWR5WlhOekxteHYKWTJGc2dobHBaM010YzNSdmNtRm5aUzVwYm1keVpYTnpMbXh2WTJGc2doUndiM0owWVd3dWFXNW5jbVZ6Y3k1cwpiMk5oYklJVWRHa3RhV1J3TG1sdVozSmxjM011Ykc5allXd3dId1lEVlIwakJCZ3dGb0FVZFN4ek1uQkMxSGVyCkNUejMzRVhwdG1FV1ZXVXdIUVlEVlIwT0JCWUVGSFVzY3pKd1F0UjNxd2s4OTl4RjZiWmhGbFZsTUJNR0ExVWQKSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRGgzaUNBNXBEM1RrREtCbUp3VApZOVY0aUx1allhclVGMmJxWDlLbFZxa2NBaUFhazZ2Z3dTL2RtNGpMc3JxblpjazhaK2RjT0dkWExqWkFxZURhCk1LbnRKUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K}
      storage-tls-certificate-internal: ${S3_STORAGE_TLS_CERTIFICATE_INTERNAL:MIIFujCCA6KgAwIBAgIUZKeh25XFYMQlrmYUPhphpOhtN34wDQYJKoZIhvcNAQELBQAwXTELMAkGA1UEBhMCREUxDDAKBgNVBAgTA05SVzERMA8GA1UEBxMIRG9ydG11bmQxDDAKBgNVBAoTAzNhczENMAsGA1UECxMES1JBQjEQMA4GA1UEAxMHS1JBQiBDQTAeFw0yNDExMTgxNTI3MzZaFw0zNDExMTYxNTI4MDZaMGwxCzAJBgNVBAYTAkRFMQwwCgYDVQQIEwNOUlcxETAPBgNVBAcTCERvcnRtdW5kMQwwCgYDVQQKEwMzYXMxDTALBgNVBAsTBEtSQUIxHzAdBgNVBAMTFktSQUIgSW50ZXJtZWRpYXRlIENBIDEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDSDuko1F9fvQ+20quW/iixN2mACAja0VaqT0vzljOaUDl0NQJvjH8QffzGeVNiTg2JX6mOXHizz8Qji5v4+cZfGUDr7Esx8+om91by4fWW8ReIZJFA8QYzEwwNVYoWfmaw4CY+1w+ZlaU3oJ2kcPeeD6/uk4uJHGYkVjw8q4MKv7c3QxKVHu/vjLsM20VNYnNnULZzftj1jhwvid0Nh0b7nU3wxbeVXmNaf3e+OXAw4dvitilSkBJY2NdLtBHbSm5FcHVcGkm8Auf3BA7KD6rLPao4rEthPJIVcY7aJn+rjEh55MKmJ/z/GD+Jk1Ni4rkMX8XugW3Pc0eZ+qRb2neAJ1lzjqYyedcx82aGipSqAEAs46HZcepSlFPcFKzo/9vgIhxwdX8V1fS0ZQGWdIoeUSl+boEEdpeA6jCX18ZCERmRrdf7I6Fj2xqDJ66OCPLlwz8aUK8MQhJSHqIlWK0MrJ9g9MDZWnDQrW337UR2mouPl83uvTnVwu6xxqH7fhPXyq2CeLBj9tB0ti4RgkWtCr3EWQ/MNNXINvJkT1Mwt5SvxSdGZXN5nHf5QGPLTl0pLjzzQbwVvddfmA2Rg8cRCwGMgigN7mpzcIAI2hnE8AwCqKw1d7bq04va7XVILRpUQNe73z12lV/WC/uxQ5hdM4z1Mrbha+ENzFhzBC1sqwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUIAcpYdQuIvuSJu2eeevWWSl1fLQwHwYDVR0jBBgwFoAUEsztUc7wQVILH+yruttkhWqfKJswDQYJKoZIhvcNAQELBQADggIBAISDKSSi57WQHNcQnkW7UvRKaYeVwCfZKov5HHRSPArX/hQnEGKAPH4aLqTYmaqFZZqD2eVcWAaUUsUI58oV3de8GQubfNfbyIUfsGSAwsCaE5KAqTBEf7725uuHkjdeWPnBadHD6st2rcNS1SKuZK8XsOZSIJLsxrGGszcnxBmn2Eo5CTf939qWSgOLGoA0HUylKcvMp3oyxieuh/oAFgHAYu6Fuic32fW8ftkSlO9yF5apStK1KYVsCKhCYbEM3kKEbykFpvWl0xlVw+rQkTg33hGfFgqvEIskt2Q/t9T3Ojg5qFUpNrqm+V+HSVQd3vrvRBPSeyWXohFPpv0Gu10kpXV/MWK/zuqAQARMPgxS6j3Eoz8lR7kdqt23ymMEqumGpRJqxNPSB4+rnnZ/afZwKIdImqoweWZ/oD1K1wQ0SkGuq4BgwZsbBKbY5FXrckdyCTdeXWbueJrLq28Dkt4AHhkm1wumSgL0swHygJinpNM3qZoihFEriMs4rvIO4UHGTVYp8o9goj1CLX1Bi9VQqWWhWi8GvVcKdrErCC6af3ciNguWlrM1heeOj7mJtdnZ/rCQncdSxb+Qb3Ei2jcaGZkCT7UFL8fykiFSCjxKGIwG0vmYLWnIOG0d8sKR7VxLqeFzHbs96ODgMxn1P42gesLEQjX4/zqEE5QTl7uy}

igs:
  outcome-issue-threshold: warning
  long-polling-timeout-secs: 15
  long-polling-interval-secs: 5
  thread:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    thread-name-prefix: "IGS-"

  demis:
    external-url: ${DEMIS_BASE_URL_EXTERNAL:https://ingress.local}
  ncapi:
    url: ${DEMIS_NETWORK_NOTIFICATION_CLEARING_API_ADDRESS:http://localhost:9070}
    apikey: ${NCAPI_TOKEN:aad3f9f00390689324a7f49c4e908fcf981dfa0563b857196e7ececf5f1eb0ea}
  ces:
    url: ${DEMIS_NETWORK_CONTENT_ENRICHMENT_SERVICE_ADDRESS:http://context-enrichment-service.demis.svc.cluster.local:8080}
  validation:
    url: ${DEMIS_NETWORK_VALIDATION_SERVICE_ADDRESS:http://validation-service.demis.svc.cluster.local:8080}

feature:
  flag: